define([], function() {
  return {
    "propertyPaneDescription": "Select which headings etc. to include in the table of contents.",
    "titleDefaultValue": "Table of Contents",
    "titleFieldDescription": "Text to display as the Table of Contents heading",
    "hideTitleFieldLabel": "Hide heading",
    "searchWebpartsLabel": "Search Webparts",
    "searchText": "Text",
    "searchMarkdown": "Markdown",
    "searchCollapsible": "Collapsible Section Header",
    "showHeadingLevelsLabel": "Show Headings",
    "showHeading1FieldLabel": "Heading 2 (Level 1)",
    "showHeading2FieldLabel": "Heading 3 (Level 2)",
    "showHeading3FieldLabel": "Heading 4 (Level 3)",
    "showHeading4FieldLabel": "Level 4",
    "listStyle": "List Icon",
    "showPreviousPageViewLabel": "Show the previous page link",
    "previousPageFieldLabel": "Link text",
    "previousPageDefaultValue": "Return to previous page",
    "showPreviousPageTitleLabel": "Above the Title",
    "showPreviousPageAboveLabel": "Above the Table of Contents",
    "showPreviousPageBelowLabel": "Below the Table of Contents",
    "enableStickyModeLabel": "Enable 'Sticky Mode'",
    "enableStickyModeDescription": "Sticky Mode fixes the Table of Contents position on the page. It is disabled automatically on small mobile devices. Use with caution as there may be undesirable side effects",
    "hideInMobileViewLabel": "Hide on small mobile devices",
    "errorToggleFieldEmpty": "This field cannot be empty, if you do not want to use this field please toggle it off!",
    "theme": "Style",
    "wpStyle": "Web part style",
    "collapsible": "Collapsible heading",
    "verticalToRight": "Move the vertical column to the left",
    "collapsibleState": "Collapsible State",
    "addScrollToTop": "Add Scroll to Top",
    "backgroundColor": "Background Color",
    "activeLinkBackgroundColor": "Active Link Background Color",
    "textSize": "Text Size",
    "textColor": "Text Color",
    "borderColor": "Border Color",
    "borderSize": "Border Size",
    "borderRoundness": "Border Roundness",
    "shadow": "Shadow",
    "enableInnerScrollingLabel" : "Enable Inner Scrolling",
    "setHeightLabel": "Set Fixed Height",
    "contentsHeightLabel": "Height"
  }
});
